module.exports = {
    WORLD_SIZE: 20,
    STATS_MINIMUM_SUM: 40,
    STAT_MINIMUM_VALUE: 4,
    STAT_MAXIMUM_VALUE: 13,
    STAT_HEALTH_BASE: 12,
    STAT_HEALTH_INCREASE: 4,
    STAT_STAMINA_BASE: 10,
    STAT_STAMINA_INCREASE: 4
}