module.exports = {
    WORLD_SIZE: 100,
    STATS_MINIMUM_SUM: 40,
    STAT_MINIMUM_VALUE: 4,
    STAT_MAXIMUM_VALUE: 13,
    STAT_HEALTH_BASE: 12,
    STAT_HEALTH_INCREASE: 4,
    STAT_STAMINA_BASE: 10,
    STAT_STAMINA_INCREASE: 4,
    MAX_MARRIAGE_AGE_GAP: 10,
    MIN_MARRIAGE_AGE: 16,
    MAX_RELATIONS_POINTS: 20,
    MIN_RELATIONS_POINTS: 10,
    MAX_RELATIONSHIP_VALUE: 10,
    MIN_RELATIONSHIP_VALUE: -10,
    GUARD_COST_MULTIPLYER: 1.2,
    GATE_COST_MULTIPLYER: 0.03,
    WALLS_COST_MULTIPLYER: 0.02,
    MOAT_COST_MULTIPLYER: 0.01,
    GUARD_COST_MAINTENANCE: 0.02,
    WALLS_COST_MAINTENANCE: 20.0,
    GATE_COST_MAINTENANCE: 60.0,
    MAOT_COST_MAINTENANCE: 40.0,   
    CONDITION_NONE_MULTIPLYER: 0.0,
    CONDITION_RUINED_MULTIPLYER: 0.4,
    CONDITION_POOR_MULTIPLYER: 0.8,
    CONDITION_GOOD_MULTIPLYER: 1.0,
    CONDITION_PERFECT_MULTIPLYER: 1.2,
    TROOP_KIGHTS_COST: 3.0,
    TROOP_MEN_AT_ARMS_COST: 0.2,
    TROOP_ARCHERS_COST: 0.1,
    TROOP_MERCENARY_COST: 0.3,
    TROOP_INFANTRY_COST: 0.1,
    TROOP_CATAPULTS_COST: 6.0,
    TROOP_KIGHTS_POWER_MIN: 3.0,
    TROOP_MEN_AT_ARMS_POWER_MIN: 0.2,
    TROOP_ARCHERS_POWER_MIN: 0.1,
    TROOP_MERCENARY_POWER_MIN: 0.3,
    TROOP_INFANTRY_POWER_MIN: 0.1,
    TROOP_CATAPULTS_POWER_MIN: 6.0,
    TROOP_KIGHTS_POWER_MAX: 3.0,
    TROOP_MEN_AT_ARMS_POWER_MAX: 0.2,
    TROOP_ARCHERS_POWER_MAX: 0.1,
    TROOP_MERCENARY_POWER_MAX: 0.3,
    TROOP_INFANTRY_POWER_MAX: 0.1,
    TROOP_CATAPULTS_POWER_MAX: 6.0
}

/*
        case ENUM_DWELLING_CONDITIONS.NONE : return 0.0;
        case ENUM_DWELLING_CONDITIONS.RUINED : return 0.0;
        case ENUM_DWELLING_CONDITIONS.POOR : return 0.0;
        case ENUM_DWELLING_CONDITIONS.GOOD : return 0.0;
        case ENUM_DWELLING_CONDITIONS.PERFECT : return 0.0;


const costMultiplyerGuards = 1.2
    const costMultiplyerGate = 0.3
    const costMultiplyerWalls = 0.2
    const costMultiplyerMaot = 0.1
    const costBaseMaintenanceGuards = dwelling.citizens * 0.02
    const costBaseMaintenanceGate = 60
    const costBaseMaintenanceWalls = 20
    const costBaseMaintenanceMaot = 40

GUARD_COST_MULTIPLYER,
    GATE_COST_MULTIPLYER,
    WALLS_COST_MULTIPLYER,
    MOAT_COST_MULTIPLYER,
    GUARD_COST_MAINTENANCE,
    GUARD_WALLS_MAINTENANCE,
    GUARD_GATE_MAINTENANCE,
    GUARD_MAOT_MAINTENANCE,
    CONDITION_NONE_MULTIPLYER,
    CONDITION_RUINED_MULTIPLYER,
    CONDITION_POOR_MULTIPLYER,
    CONDITION_GOOD_MULTIPLYER,
    CONDITION_PERFECT_MULTIPLYER


*/